---
  - name: "Update/upgrade packages"
    become: true
    shell: apt -y update && apt -y upgrade

  - name: "Install node repository"
    become: true
    shell: |
      curl -sL https://deb.nodesource.com/setup_13.x | bash -

  - name: "Install node 13"
    become: true
    apt:
      name: ["nodejs"]
      state: latest
      update_cache: yes

  - name: "Install PM2 Globally"
    npm:
      name: pm2
      global: yes