---
  - name: "Update/upgrade packages"
    become: true
    shell: apt -y update && apt -y upgrade

  - name: "Remove unneeded dependencies"
    become: true
    apt:
      autoremove: yes

  - name: "Install npm and nodejs"
    become: yes
    apt:
      name: ["npm", "nodejs"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present