---

- name: "Create backend directory"
  file:
    path: ~/backend
    state: directory

- name: "Unarchive files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Start app"
  shell: |
    cd ~/backend
    npm i
    pm2 stop default
    pm2 start npm -- start

